GET http://localhost:3001/api/blogs 

###
POST http://localhost:3001/api/blogs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VybmFtZSIsImlkIjoiNjU1NDU5MWU2MTVlZmFmY2JlNjUwZTcyIiwiaWF0IjoxNzAwMDI3MDY0fQ.1dUrpkvk9xyD7OyNrNDpLDLNR0_ofitRsxVsxTQUa8M

{
    "title": "test title three",
    "author": "Andreeseen horowitz",
    "url": "https://a16z.com/why-software-is-eating-the-world/",
    "likes": 100
}

###
POST http://localhost:3001/api/blogs 
Content-Type: application/json

{
    "title": "Why is SOFTWARE eating the world",
    "author": "Andreeseen horowitz",
    "url": "https://a16z.com/why-software-is-eating-the-world/",
    "likes": 100
}