POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
    "title": "Why is SOFTWARE eating the world",
    "author": "Andreeseen horowitz",
    "url": "https://a16z.com/why-software-is-eating-the-world/",
    "likes": 100
}