GET http://localhost:3001/api/blogs 

###
POST http://localhost:3001/api/blogs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik0gU2FubmF5IiwiaWQiOiI2NTU0MjA2MGFkYjY2NGNkODcyZDBmY2QiLCJpYXQiOjE3MDAwMTI3MTh9.cWcKg0FvpB0AkWon6U5rNAutgYH12ALDIBX2lgHnkpw

{
    "title": "Why is SOFTWARE eating the world",
    "author": "Andreeseen horowitz",
    "url": "https://a16z.com/why-software-is-eating-the-world/",
    "likes": 100
}

###
POST http://localhost:3001/api/blogs 
Content-Type: application/json

{
    "title": "Why is SOFTWARE eating the world",
    "author": "Andreeseen horowitz",
    "url": "https://a16z.com/why-software-is-eating-the-world/",
    "likes": 100
}